version: "3.8"
services:
  ldt-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ldt-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: on-failure


  